/**
 * Capture real CodeRabbit verdicts for the staged PRs and write them into
 * lib/fixtures/coderabbit-cache.ts.
 *
 *     npm run record:coderabbit            # all staged PRs
 *     npm run record:coderabbit -- pr-101  # just one
 *
 * WHY THIS EXISTS: CodeRabbit reviews take minutes and free-plan CLI reviews
 * are rate limited to roughly three an hour. That is fine for development and
 * fatal for a live demo. So we capture genuine verdicts ahead of time and read
 * them back on stage. The verdict is real; only the timing is pre-arranged, and
 * you should say that out loud rather than implying a live call.
 *
 * HOW IT WORKS: for each PR we materialise the `after` code into a scratch git
 * repo as an uncommitted change over the `before` code, so the CLI sees exactly
 * the diff a reviewer would see, then run `coderabbit review --agent`.
 *
 * PREREQUISITES:
 *   curl -fsSL https://cli.coderabbit.ai/install.sh | sh
 *   coderabbit auth login
 *
 * Budget 15-40 minutes for a full run. Start it and go build something else.
 */

import "dotenv/config";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { STAGED_PRS, getPR } from "../lib/fixtures/prs";
import { digestStagedPR, runCodeRabbitCLI } from "../lib/adapters/coderabbit";
import type { CodeRabbitReview, StagedPR } from "../lib/types";

const OUT = join(process.cwd(), "lib/fixtures/coderabbit-cache.ts");

function serialize(cache: Record<string, CodeRabbitReview>): string {
  return `/**
 * Pre-recorded CodeRabbit verdicts, keyed by staged PR id.
 *
 * GENERATED by scripts/record-coderabbit.ts on ${new Date().toISOString()}.
 * Re-run 'npm run record:coderabbit' after changing any staged PR.
 */

import type { CodeRabbitReview } from "../types";

export const CODERABBIT_CACHE: Record<string, CodeRabbitReview> = ${JSON.stringify(cache, null, 2)};
`;
}

async function main() {
  const only = process.argv.slice(2).filter((a) => !a.startsWith("-"));
  const targets = only.length > 0 ? only.map((id) => getPR(id)).filter(Boolean) as StagedPR[] : STAGED_PRS;

  if (targets.length === 0) {
    console.error("No matching PRs. Known ids:", STAGED_PRS.map((p) => p.id).join(", "));
    process.exit(1);
  }

  console.log(`Recording CodeRabbit verdicts for ${targets.length} PR(s). This is slow.\n`);

  const cache: Record<string, CodeRabbitReview> = {};

  for (const pr of targets) {
    console.log(`  ${pr.id}  ${pr.title}`);
    console.log("         staging repository and invoking CLI…");
    const started = Date.now();
    try {
      const review = await runCodeRabbitCLI(pr);
      cache[pr.id] = {
        verdict: review.verdict,
        findings: review.findings,
        raw: review.raw,
        source: "cache",
        recordedAt: new Date().toISOString(),
        prDigest: digestStagedPR(pr),
      };
      console.log(
        `         ${review.verdict} · ${review.findings.length} finding(s) · ${Math.round((Date.now() - started) / 1000)}s\n`,
      );
    } catch (err) {
      console.error(`         FAILED: ${err instanceof Error ? err.message : err}\n`);
    }
  }

  if (Object.keys(cache).length === 0) {
    console.error("Nothing recorded. Existing cache left untouched.");
    process.exit(1);
  }

  // Merge over whatever is already recorded so a single-PR run does not wipe the rest.
  const { CODERABBIT_CACHE: existing } = await import("../lib/fixtures/coderabbit-cache");
  writeFileSync(OUT, serialize({ ...existing, ...cache }));
  console.log(`Wrote ${OUT}`);
  console.log("Review the diff before committing — check the verdicts are what you expect on stage.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
